name = "NURBS"
uuid = "dde13934-061e-461b-aa91-2c0fad390a0d"
authors = ["Bernd Hofmann <bernd.hofmann@tum.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
